# Actions 模組初始化檔案
# 明確指定要導出的 Action 類別，避免 _BaseAction 被註冊

# 注意：Rasa SDK 會自動掃描模組中所有繼承自 Action 的類別
# _BaseAction 使用下劃線開頭，並且 name() 返回 None，避免被註冊

# 導入所有 Action 類別
from .actions import (
    ActionFindNearestToilet,
    ActionFindNearestWater,
    ActionFindNearestTrash,
    ActionShowRoute,
    ActionQueryCampusStats,
    ActionCalculateDistance,
    ActionGetCurrentTime,
    ActionReportFacilityIssue,
    ActionProvideSuggestions,
    ActionRememberContext,
    ActionUpdateFacilityStatus,
    ActionGreet,
    ActionGoodbye,
    ActionSetLanguage,
    ActionUpdateFloorStatus,
    ActionQueryFloorStatus,
    ActionReportFacilityProblem,
    ActionQueryBuildingFacilities,
    ActionGetSmartRoute,
    ActionQueryFacilityHistory,
    ActionGetStatistics,
    ActionSetPreference,
    ActionGetPreferences,
    ActionQuickReport,
    ActionQueryIssueHistory,
    ActionGetUserLocation,
    ActionFindNearestFunctionalFacility,
    ActionQueryFacilityGPS,
    ActionQueryFacilityStatus,
    ActionNavigateToFunctionalFacility,
    ActionGetFacilityGPSPoints,
    ActionQueryNearbyFacilitiesStatus,
    ActionCompareFacilities,
    ActionGetFacilitiesByStatus,
    ActionGetFacilitiesSortedByDistance,
    ActionRecommendFacility,
    ActionSmartSuggestions,
    ActionFormatRichResponse,
    ActionGetFacilityStatistics,
    ActionBatchQueryFacilities,
    ActionShowProgress,
    ActionSmartErrorRecovery,
)

from .campus_info_actions import (
    ActionAskCampusEvents,
    ActionAskBuildingInfo,
    ActionAskEmergencyContact,
    ActionAskParkingInfo,
    ActionAskDiningInfo,
    ActionAskLibraryHours,
    ActionAskWeather,
    ActionAskCampusTips,
)

# 明確指定要導出的類別（Rasa SDK 可能會使用這個列表）
__all__ = [
    'ActionFindNearestToilet',
    'ActionFindNearestWater',
    'ActionFindNearestTrash',
    'ActionShowRoute',
    'ActionQueryCampusStats',
    'ActionCalculateDistance',
    'ActionGetCurrentTime',
    'ActionReportFacilityIssue',
    'ActionProvideSuggestions',
    'ActionRememberContext',
    'ActionUpdateFacilityStatus',
    'ActionGreet',
    'ActionGoodbye',
    'ActionSetLanguage',
    'ActionUpdateFloorStatus',
    'ActionQueryFloorStatus',
    'ActionReportFacilityProblem',
    'ActionQueryBuildingFacilities',
    'ActionGetSmartRoute',
    'ActionQueryFacilityHistory',
    'ActionGetStatistics',
    'ActionSetPreference',
    'ActionGetPreferences',
    'ActionQuickReport',
    'ActionQueryIssueHistory',
    'ActionGetUserLocation',
    'ActionFindNearestFunctionalFacility',
    'ActionQueryFacilityGPS',
    'ActionQueryFacilityStatus',
    'ActionNavigateToFunctionalFacility',
    'ActionGetFacilityGPSPoints',
    'ActionQueryNearbyFacilitiesStatus',
    'ActionCompareFacilities',
    'ActionGetFacilitiesByStatus',
    'ActionGetFacilitiesSortedByDistance',
    'ActionRecommendFacility',
    'ActionSmartSuggestions',
    'ActionFormatRichResponse',
    'ActionGetFacilityStatistics',
    'ActionBatchQueryFacilities',
    'ActionShowProgress',
    'ActionSmartErrorRecovery',
    'ActionAskCampusEvents',
    'ActionAskBuildingInfo',
    'ActionAskEmergencyContact',
    'ActionAskParkingInfo',
    'ActionAskDiningInfo',
    'ActionAskLibraryHours',
    'ActionAskWeather',
    'ActionAskCampusTips',
]
